AllCops:
    DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false